### ISSUE TITLE
Single quotes are stripped from decoded strings

### ISSUE THREAD

**Issue by jdessartcs** [pbhogan/TinyJSON#10]
Repro steps:
 - create JSON with escaped single quotes within strings
 - decode JSON
 - observe lack of single quotes in the output

**Comment by pbhogan** [comment]
JSON does not escape single quotes in strings (http://www.json.org/)

TinyJSON currently swallows the next character, but it should probably throw an exception as any character following \ other than "/\bfnrtu is technically illegal.
