### ISSUE TITLE
How to convert object type？

### ISSUE THREAD

**Issue by pyengwoei** [pbhogan/TinyJSON#11]
public string marketid = "0";   //right
  public string matchcode = "0";  //right
  public object kickofftime;   //if (proxyObject == null)
			{
				throw new InvalidCastException( "ProxyObject expected when decoding into '" + type.FullName + "'." );
			}

**Comment by pbhogan** [comment]
Your code and question seems incomplete. Please elaborate more fully on what you're asking.
