### ISSUE TITLE
Consider adding a baseClassFirst flag?

### ISSUE THREAD

**Issue by powof2** [pbhogan/TinyJSON#12]
hi,
thank you for the great tool.

how about adding a flag so tinyjson can export base class infos first?

something like this :
```
public enum EncodeOptions
{
	None = 0,
	PrettyPrint = 1,
	NoTypeHints = 2,
	IncludePublicProperties = 4,
	BaseFirst = 8, // <-- new flag
}
```

in Encoder.cs:

```
// before:
// var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

// after:
var types = new List<Type>();
types.Add(type);

var baseType = type;
while (baseType.BaseType != typeof(Object))
{
	types.Add(baseType.BaseType);
	baseType = baseType.BaseType;
}

if (types.Count > 1 && (0 != (options & EncodeOptions.BaseFirst)))
{
	// reverse types so it will export base classes first
	types.Reverse();
}

var fields = new List<FieldInfo>();
foreach (var t in types)
{
	// new binding flag : BindingFlags.DeclaredOnly
	fields.AddRange(t.GetFields(BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance));
}
```

and:

```
// before :
// var properties = type.GetProperties( BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance );

//after:
var properties = new List<PropertyInfo>();

foreach (var t in types)
{
	properties.AddRange(t.GetProperties( BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance ));
}
```

thank you.

**Comment by pbhogan** [comment]
Not sure I understand the point of this? The order of keys in a JSON object should be irrelevant.

**Comment by powof2** [comment]
in the following example:
```
enum AnimalType
{
	kAnimalCat = 0,
	kAnimalHuman,	
}

class Animal
{
	public AnimalType type;	
}

class Cat : Animal
{
	public int legCount;
}

class Human : Animal
{	
	public int legCount;
}
```

if export derived class info first, we got something like this :
```
[
	{
		"legCount" : 4,
		"type" : "kAnimalCat"		
	},

	{
		"legCount" : 2,
		"type" : "kAnimalHuman"		
	}
]
```
that means, for each class, we'll have to loop to the last tag ("type" in this example) to know what kind of animal it is.
If we export base class info ("type" in this example) first, we already know the animal type by just checking the tag of its first child and create the class of the type.

**Comment by powof2** [comment]
in the following example:
```
enum AnimalType
{
	kAnimalCat = 0,
	kAnimalHuman,	
}

class Animal
{
	public AnimalType type;	
}

class Cat : Animal
{
	public int legCount;
}

class Human : Animal
{	
	public int legCount;
}
```

if export derived class info first, we got something like this :
```
[
	{
		"legCount" : 4,
		"type" : "kAnimalCat"		
	},

	{
		"legCount" : 2,
		"type" : "kAnimalHuman"		
	}
]
```
that means, for each class, we'll have to loop to the last tag ("type" in this example) to know what kind of animal it is.

If we export base class info ("type" in this example) first, we already know the animal type by just checking the tag of its first child and create the class of the type.

**Comment by pbhogan** [comment]
Why aren't you using the type hint system in place for this purpose? And secondly, objects should be decoded into a dictionary, so there's no iteration to get to type, just query animal["type"]?

It sounds like you're parsing your JSON in something else?

**Comment by powof2** [comment]
yeah, i am using [gason](https://github.com/vivkin/gason) to scan and load in c++.

**Comment by pbhogan** [comment]
Okay, I'll take a look at adding it when I get a chance. The codebase changes rarely anymore, so you should be good for a while with your patch.

**Comment by pbhogan** [comment]
Sorry this took so long to get to. The flag `EncodeOptions.EnforceHeirarchyOrder` will now do this.
