### ISSUE TITLE
How to convert Variant back to json string?

### ISSUE THREAD

**Issue by AndreyPostelzhuk** [pbhogan/TinyJSON#13]
Variant.ToString() doesn't work. JSON.Dump() doesn't work. The only way that I found is to use Dto object. But what if it's completely generic data and structure is unknown?

**Comment by pbhogan** [comment]
This is not currently possible. Variants are intended to be temporarily used to convert JSON to structured data or in a readonly capacity. And then structured data can be output to JSON. TinyJSON is not intended for completely unstructured, generic data. It's specifically designed to assist in the serialization of existing C# structures.
