### ISSUE TITLE
Exception when serializing an exception :P

### ISSUE THREAD

**Issue by crystalbyte** [pbhogan/TinyJSON#16]
Calling `CanRead` on property `IsTransient` in type `System.Exception` throws a MissingMethodException.

Unity: 2020.1.14f1
IL2CPP
.NETStandard 2.0

![image](https://user-images.githubusercontent.com/548964/100766378-ddbd2a80-33f8-11eb-965e-482fbb44bb31.png)

The error is thrown by the following line.
![image](https://user-images.githubusercontent.com/548964/100766332-d269ff00-33f8-11eb-84f7-efe9acfc0e1f.png)

**Comment by pbhogan** [comment]
Not sure why you're trying to JSON encode an exception but this sounds more like a bug in Unity IL2CPP unless you can replicate it outside of Unity using a standard compiler.

Properties returned by `System.Type.GetProperties()` are expected to exist, which is what `GetPropertiesForType(type)` is calling.

I suppose you could wrap that block in a try/catch for `MissingMethodException` as a workaround.

**Comment by crystalbyte** [comment]
The reason we want to serialize an exception is because we are using the JSON library to log exceptions to out backend.

I guess you are correct as this seems to be an upstream issue with Unity, I will close this for now and post it on their issue tracker.

Thanks anyways ::)
