### ISSUE TITLE
Please use correct .NET naming convention

### ISSUE THREAD

**Issue by kaalus** [pbhogan/TinyJSON#3]
JSON -> Json

See:
https://msdn.microsoft.com/en-us/library/ms182249(v=vs.80).aspx

That's why there exists XmlReader/XmlDocument, not XMLReader/XMLDocument.

**Comment by pbhogan** [comment]
I have no interest in conforming to anyone's conventions other than my own. Nor am I interested in breaking the projects already using this library.
