### ISSUE TITLE
InvalidCastException On Loading Dictionary with Enum as Keys

### ISSUE THREAD

**Issue by AquaGeneral** [pbhogan/TinyJSON#5]
I'm using the latest version's source downloaded directly from GitHub in Unity 5.2.3.

I have a class that is to be serialized. It contains a bunch of fields (that part works) and a Dictionary<TerrainMode, MyClass> (TerrainMode is the enum).

When loading the JSON back it hits an exception when trying to convert the string representation of  TerrainMode to the actual enum representation.

Stacktrace:
> InvalidCastException: Value is not a convertible object: System.String to JesseStiller.TerrainFormerExtension.TerrainMode
System.Convert.ToType (System.Object value, System.Type conversionType, IFormatProvider provider, Boolean try_target_to_type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Convert.cs:2941)
System.String.System.IConvertible.ToType (System.Type targetType, IFormatProvider provider) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/String.cs:2420)
System.Convert.ToType (System.Object value, System.Type conversionType, IFormatProvider provider, Boolean try_target_to_type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Convert.cs:2937)
System.Convert.ChangeType (System.Object value, System.Type conversionType) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Convert.cs:2490)
TinyJSON.JSON.DecodeDictionary[TerrainMode,BrushSettings] (TinyJSON.Variant data) (at Assets/TerrainFormer/TinyJSON/Source/JSON.cs:366)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
TinyJSON.JSON.DecodeType[Dictionary`2] (TinyJSON.Variant data) (at Assets/TerrainFormer/TinyJSON/Source/JSON.cs:227)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
TinyJSON.JSON.DecodeType[Settings] (TinyJSON.Variant data) (at Assets/TerrainFormer/TinyJSON/Source/JSON.cs:300)

**Comment by pbhogan** [comment]
My guess is you have the enum as the key in the Dictionary? I don't think that works currently... right now it looks like keys need to be a primitive type that can directly converted from a string: https://github.com/pbhogan/TinyJSON/blob/master/TinyJSON/JSON.cs#L366

It might actually be possible to support enums as keys... but I'm not 100% sure. Since we know the target type it should be as simple as what is done for the value side: https://github.com/pbhogan/TinyJSON/blob/master/TinyJSON/JSON.cs#L177

We would also need to ensure the enum is being encoded as its full qualified name and not a number string.

**Comment by pbhogan** [comment]
Fixed by #7.
