### ISSUE TITLE
Include public readable properties on JSON output by default

### ISSUE THREAD

**Issue by ksanchezm** [pbhogan/TinyJSON#9]
I think the most intuitive behaviour would be to include public readable properties on the output. For example, if using a DTO with lots of properties then it becomes cumbersome to add an attribute to everyone of them. And if a property is public, it would make sense to expose it on the resultant JSON anyway.

**Comment by pbhogan** [comment]
This is counter to every other C# serialization library and how it works in .NET and Unity standard serialization.

I might add an option to EncodeOptions to allow toggling it away from the default, but I don't think it's wise to change the default, as it'll break everyone's existing project who is expecting the normal behavior.

**Comment by ksanchezm** [comment]
serializing this clas:

public foo 
{
    public string Name { get; set;}
    public int Age {get; set; }
}

Using TinyJSON the output (with NoTypeHint) is this: {}

Using Json.Net the output is this: {"Name":"Peter","Age":10}



I can't argue about the Unity standard serialization (I'm not into mobile games development); I'm just trying to serialize a POCO as Json and send it to an api controller. I'm 100% with you about breaking the _expected_ behaviour of your old clients but I do find the approach counterintuitive (I mean, they are public properties after all). Anyway, adding an EncodeOption for that would be an excellent choice for this predicament.



Also, I want to congratulate you on your work so far; I discovered your TinyJSON library while searching for a Tiny Json library (pun intended) :P I work with clients that have extremely low bandwidth (think 3rd world countries) and I really need to keep the .EXE size small (auto updates and the like). Your library allowed me to reduce my executable size from 300KB to ~150KB just by eliminating the Json.Net dependency (I'm using Costura.Fody to embed references.) So, you have my thanks!

**Comment by pbhogan** [comment]
Implemented.
